---
- name: configure dns servers as reverse DNS  
  hosts: localhost 
  become: yes
  tasks:
    # Step 1: Ensure BIND (named) is installed
    - name: Ensure BIND (named) is installed
      package:
        name: bind
        state: present

    # Step 2: Get the server's primary IP address
    - name: Get the server's primary IP address
      command: ip addr show
      register: ip_output

    - name: Extract primary IP address
      set_fact:
        ip_address: "{{ ip_output.stdout | regex_search('inet ([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+)/', '\\1') }}"
      when: ip_output.stdout is search('inet ([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+)')

    - name: Verify primary IP address extraction
      debug:
        msg: "Extracted IP address is {{ ip_address }}"

    # Step 3: Get the network address from the primary IP
    - name: Get the network address (first three octets)
      set_fact:
        network_address: "{{ ip_address | regex_replace('\\.[0-9]+$', '') }}"

    - name: Verify network address extraction
      debug:
        msg: "Network address (first three octets) is {{ network_address }}"

    # Step 4: Calculate the reverse zone based on the network address
    - name: Calculate the reverse zone
      set_fact:
        reverse_zone: "{{ network_address.split('.')[2] }}.{{ network_address.split('.')[1] }}.{{ network_address.split('.')[0] }}.in-addr.arpa"

    - name: Verify reverse zone calculation
      debug:
        msg: "Calculated reverse zone is {{ reverse_zone }}"


    # Step 5: Backup /etc/named.conf
    - name: Backup /etc/named.conf
      copy:
        src: /etc/named.conf
        dest: /etc/named.conf.bak
        remote_src: yes

        # Pre-check for existing forward zone for linuxcbt.external
    - name: Check if forward zone for linuxcbt.external exists in /etc/named.conf
      command: grep -q 'zone "linuxcbt.external"' /etc/named.conf
      register: zone_linuxcbt_external
      ignore_errors: true
      changed_when: false

    # Step 6: Configure forward zone in /etc/named.conf if not present
    - name: Ensure forward zone for linuxcbt.external is configured in /etc/named.conf
      blockinfile:
        path: /etc/named.conf
        marker: "### Added by Ansible - Forward Zone ###"
        block: |
          zone "linuxcbt.external" IN {
              type slave;
              masters { {{ ip_address }}; };
              file "/var/named/slaves/linuxcbt.external";
              allow-update { none; };
          };
      when: zone_linuxcbt_external.rc != 0  # Only add if grep didn’t find the zone


    - name: Ensure reverse zone for linuxcbtserv2 is configured in /etc/named.conf
      blockinfile:
        path: /etc/named.conf
        marker: "### Added by Ansible - Reverse Zone ###"
        block: |
          zone "{{ reverse_zone }}" IN {
              type master;
              file "/var/named/{{ reverse_zone }}.zone";
              allow-update { none; };
          }

    # Step 7: Create the reverse zone file with PTR records
    - name: Check if reverse zone file exists
      stat:
        path: "/var/named/{{ reverse_zone }}.zone"
      register: reverse_zone_file

    - name: Create reverse zone file with PTR records if not present
      blockinfile:
        path: "/var/named/{{ reverse_zone }}.zone"
        marker: "### Added by Ansible - Reverse Zone File ###"
        create: yes
        block: |
          $TTL 1800
          @ IN SOA linuxcbtserv2.linuxcbt.internal. dns-admin.linuxcbt.internal. (
                      2017121601 ; serial
                      1D         ; refresh
                      1H         ; retry
                      1W         ; expire
                      3H )       ; minimum
          @ IN NS linuxcbtserv2.linuxcbt.internal.
          @ IN NS linuxcbtserv1.linuxcbt.internal.
          {{ ip_address.split('.')[3] }} IN PTR linuxcbtserv2.linuxcbt.internal.

      when: not reverse_zone_file.stat.exists

    # Step 8: Apply file permissions and SELinux context
    - name: Set ownership for reverse zone file
      file:
        path: "/var/named/{{ reverse_zone }}.zone"
        owner: root
        group: named
        mode: '0644'

    - name: Restore SELinux context on reverse zone file
      command: restorecon -v /var/named/{{ reverse_zone }}.zone

    - name: Set SELinux context for named_zone_t on reverse zone file
      command: chcon -t named_zone_t /var/named/{{ reverse_zone }}.zone

    # Step 9: Check named configuration syntax and restart the service
    - name: Check named configuration syntax
      command: named-checkconf /etc/named.conf
      register: check_conf
      failed_when: check_conf.rc != 0

    - name: Check reverse zone configuration syntax
      command: named-checkzone {{ reverse_zone }} /var/named/{{ reverse_zone }}.zone
      register: check_zone
      failed_when: check_zone.rc != 0

    - name: Restart named service
      systemd:
        name: named
        state: restarted

    - name: Display completion message
      debug:
        msg: "BIND configuration for linuxcbtserv2 is complete."
