# secret.yml
db_password: "MySuperSecretPassword"  # Database password
api_key: "XYZ1234SecureAPIKey"        # API key for external service
#### Template File: `app_config.j2`
# app_config.j2
database:
  password: "{{ db_password }}"  # Placeholder for the database password
api:
  key: "{{ api_key }}"            # Placeholder for the API key
#### Playbook: `deploy.yml`
---
- name: Deploy application using Vault for secrets
  hosts: localhost  # Targeting the localhost for deployment
  become: yes        # Run tasks with elevated privileges
  vars_files:
    - secret.yml  # Encrypted file containing sensitive variables
  tasks:
    - name: Create config file with sensitive data
      template:
        src: app_config.j2  # Jinja2 template to render
        dest: /etc/app/config.yml  # Destination for the rendered config file
    - name: Print sensitive variables for demonstration
      debug:
        msg: "DB Password: {{ db_password }}, API Key: {{ api_key }}"
