---
- hosts: webservers  # Targeting the group of web servers
  become: yes  # Run tasks with elevated privileges
  vars_files:
    - /home/ansible/secret  # Load variables from an encrypted file
  tasks:
# Equivalent Linux command: sudo yum install httpd -y
      # Ad hoc Ansible command: ansible webservers -m yum -a "name=httpd state=latest"
    - name: Install Apache
      yum: 
        name: httpd 
        state: latest  # Ensure Apache is installed with the latest version
     # Equivalent Linux command: sudo cp /home/ansible/assets/httpd.conf /etc/httpd/conf/httpd.conf
      # Ad hoc Ansible command: ansible webservers -m template -a "src=/home/ansible/assets/httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf"
    - name: Configure httpd as necessary
      template:
        src: /home/ansible/assets/httpd.conf.j2  # Jinja2 template for httpd configuration
        dest: /etc/httpd/conf/httpd.conf  # Destination for the configuration file
	# Equivalent Linux command: sudo mkdir -p /var/www/html/secure && sudo chmod 0755 /var/www/html/secure
      # Ad hoc Ansible command: ansible webservers -m file -a "state=directory path=/var/www/html/secure mode=0755"
    - name: Create secure directory
      file:
        state: directory  # Ensure the directory exists
        path: /var/www/html/secure  # Path for the secure directory
        mode: '0755'  # Set directory permissions
	# Equivalent Linux command: sudo cp /home/ansible/assets/htaccess.j2 /var/www/html/secure/.htaccess
      # Ad hoc Ansible command: ansible webservers -m template -a "src=/home/ansible/assets/htaccess.j2 dest=/var/www/html/secure/.htaccess"
    - name: Deploy htaccess file
      template:
        src: /home/ansible/assets/htaccess.j2  # Jinja2 template for .htaccess file
        dest: /var/www/html/secure/.htaccess  # Destination for the .htaccess file
      # Equivalent Linux command: sudo yum install python-passlib -y
      # Ad hoc Ansible command: ansible webservers -m yum -a "name=python-passlib state=latest"
    - name: Make sure passlib is installed for htpasswd module
      yum: 
        name: python-passlib 
        state: latest  # Ensure python-passlib is installed for managing passwords
    - name: Create users for basic auth
      htpasswd:
        path: /var/www/html/secure/.passwdfile  # File to store user credentials
        name: "{{ secure_user }}"  # User
