---
  - name: Setup DNS Caching-Only Server
    hosts: localhost  # Replace with your actual target hosts
    become: yes  # Use sudo to execute tasks with elevated privileges
    vars:
      se_linux:
        - named_write_master_zones
        - allow_httpd_mod_auth_ntlm_winbind
        - allow_ypbind
    tasks:
      - name: Ensure required packages are installed
        yum:
          name:
            - net-tools
            - firewalld
            - unbound
            - bind
            - bind-utils
          state: present
      
      - name: Enable and start firewalld
        service:
          name: firewalld
          state: started
          enabled: true
  
      - name: Configure firewalld to only allow DNS traffic
        firewalld:
          service: dns
          permanent: true
          state: enabled
      
      - name: Configure firewalld to allow port forwarding
        firewalld: 
          zone: public
          port: 53/tcp
          permanent: true
          state: enabled
      

      - name: Replace all instances of 'localhost' with 'any' in /etc/named.conf
        replace:
          path: /etc/named.conf
          regexp: 'localhost'
          replace: 'any'
  
      - name: Add required lines in the options block
        lineinfile:
          path: /etc/named.conf
          line: "{{ item }}"
          state: present
          insertafter: 'options {'
        loop:
          - "listen-on port 53 { 127.0.0.1; };"
          - "listen-on-v6 port 53 { ::1; };"
  
      - name: Validate named.conf configuration
        command: named-checkconf /etc/named.conf
        register: named_check
        ignore_errors: yes
      
      - name: enable security for dns services
        seboolean:
          name: "{{item}}"
          state: true
          persistent: true
        loop: "{{se_linux}}"  

      - name: Display named-checkconf output
        debug:
          var: named_check.stdout
  
      - name: Restart named service if configuration is valid
        systemd:
          name: named
          state: restarted
        when: named_check.rc == 0
  
      - name: Handle configuration validation failure
        fail:
         msg: "Configuration validation failed. Please check /etc/named.conf."
        when: named_check.rc != 0