---
- name: Set up HAProxy as Load Balancer on Host 3
  hosts: load_balancer
  become: yes
  tasks:
    - name: Install HAProxy
      ansible.builtin.yum:
        name: haproxy
        state: present

    - name: Enable and start HAProxy service
      ansible.builtin.systemd:
        name: haproxy
        enabled: true
        state: started
